language: nix
env:
  matrix:
    - PACKAGE_SET=pytest
    - PACKAGE_SET=flake8
    - PACKAGE_SET=django
    - PACKAGE_SET=pypi2nix
    - PACKAGE_SET=packaging
script:
  - nix-shell --command 'python build_packages.py --build-only --package-set "${PACKAGE_SET}"'
